# Generated by Django 4.0.5 on 2022-06-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_us', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='id_us')),
                ('nombre_us', models.CharField(max_length=100, verbose_name='nombre_us')),
                ('apellido_us', models.CharField(max_length=100, verbose_name='apellido_us')),
                ('correo_us', models.CharField(max_length=100, verbose_name='correo_us')),
                ('dir_us', models.CharField(max_length=150, verbose_name='dir_us')),
                ('fnac_us', models.DateField(verbose_name='fnac_us')),
                ('estado_us', models.CharField(max_length=2, verbose_name='estado_us')),
                ('tipo_us', models.CharField(max_length=50, verbose_name='tipo_us')),
                ('contra_us', models.CharField(max_length=8, verbose_name='contra_us')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
